#include <stdio.h>
#include "debug.h"

uint16_t disassemble(Cpu* cpu) {
    printf("%04x        ", cpu->pc);

    uint8_t opcode = cpu_read_byte(cpu);
    uint16_t bytes_instruction = 1;
    uint16_t word = cpu_read_word(cpu);
    uint8_t highorder = word >> 8;
    uint8_t loworder = word & 0xFF;

    switch (opcode) {
        case 0x00: printf("NOP"); break;
        case 0x01: printf("LXI      B = %02x C = %02x", highorder, loworder);
            bytes_instruction = 3;
            break;
        case 0x02: printf("STAX     $BC = A"); break;
        case 0x03: printf("INX      BC++"); break;
        case 0x04: printf("INR      B++"); break;
        case 0x05: printf("DCR      B--"); break;
        case 0x06: printf("MVI      B = %02x", loworder);
            bytes_instruction = 2;
            break;
        case 0x07: printf("RLC      A << 1"); break;
        case 0x08: printf("NOP"); break;
        case 0x09: printf("DAD      HL += BC"); break;
        case 0x0A: printf("LDAX     A = $BC"); break;
        case 0x0B: printf("DCX      BC--"); break;
        case 0x0C: printf("INR      C++"); break;
        case 0x0D: printf("DCR      C--"); break;
        case 0x0E: printf("MVI      C = %02x", loworder);
            bytes_instruction = 2;
            break;
        case 0x0F: printf("RRC      A >> 1"); break;
        case 0x10: printf("NOP"); break;
        case 0x11: printf("LXI      D = %02x E = %02x", highorder, loworder);
            bytes_instruction = 3;
            break;
        case 0x12: printf("STAX     $DE = A"); break;
        case 0x13: printf("INX      DE++"); break;
        case 0x14: printf("INR      D++"); break;
        case 0x15: printf("DCR      D--"); break;
        case 0x16: printf("MVI      D = %02x", loworder);
            bytes_instruction = 2;
            break;
        case 0x17: printf("RAL      A << 1"); break;
        case 0x18: printf("NOP"); break;
        case 0x19: printf("DAD      HL += DE"); break;
        case 0x1A: printf("LDAX     A = $DE"); break;
        case 0x1B: printf("DCX      DE--"); break;
        case 0x1C: printf("INR      E++"); break;
        case 0x1D: printf("DCR      E--"); break;
        case 0x1E: printf("MVI      E = %02x", loworder);
            bytes_instruction = 2;
            break;
        case 0x1F: printf("RAR      A >> 1"); break;
        case 0x20: printf("NOP"); break;
        case 0x21: printf("LXI      H = %02x L = %02x", highorder, loworder);
            bytes_instruction = 3;
            break;
        case 0x22: printf("SHLD     %02x = H %02x = L", highorder, loworder);
            bytes_instruction = 3;
            break;
        case 0x23: printf("INX      HL++"); break;
        case 0x24: printf("INR      H++"); break;
        case 0x25: printf("DCR      H--"); break;
        case 0x26: printf("MVI      H = %02x", loworder);
            bytes_instruction = 2;
            break;
        case 0x27: printf("DAA      Decimal adjust accumulator"); break;
        case 0x28: printf("NOP"); break;
        case 0x29: printf("DAD      HL += HL"); break;
        case 0x2A: printf("LHLD     H = %02x L = %02x", highorder, loworder);
            bytes_instruction = 3;
            break;
        case 0x2B: printf("DCX      HL--"); break;
        case 0x2C: printf("INR      L++"); break;
        case 0x2D: printf("DCR      L--"); break;
        case 0x2E: printf("MVI      L = %02x", loworder);
            bytes_instruction = 2;
            break;
        case 0x2F: printf("CMA      A = !A"); break;
        case 0x30: printf("NOP"); break;
        case 0x31: printf("LXI      SP = %02x%02x", highorder, loworder);
            bytes_instruction = 3;
            break;
        case 0x32: printf("STA      %02x%02x = A", highorder, loworder);
            bytes_instruction = 3;
            break;
        case 0x33: printf("INX      SP++"); break;
        case 0x34: printf("INR      $HL++"); break;
        case 0x35: printf("DCR      $HL--"); break;
        case 0x36: printf("MVI      $HL = %02x", loworder);
            bytes_instruction = 2;
            break;
        case 0x37: printf("STC      Set carry flag"); break;
        case 0x38: printf("NOP"); break;
        case 0x39: printf("DAD      HL += SP"); break;
        case 0x3A: printf("LDA      A = $%02x%02x", highorder, loworder);
            bytes_instruction = 3;
            break;
        case 0x3B: printf("DCX      SP--"); break;
        case 0x3C: printf("INR      A++"); break;
        case 0x3D: printf("DCR      A--"); break;
        case 0x3E: printf("MVI      A = %02x", loworder);
            bytes_instruction = 2;
            break;
        case 0x3F: printf("CMC      C = !C"); break;
        case 0x40: printf("MOV      B = B"); break;
        case 0x41: printf("MOV      B = C"); break;
        case 0x42: printf("MOV      B = D"); break;
        case 0x43: printf("MOV      B = E"); break;
        case 0x44: printf("MOV      B = H"); break;
        case 0x45: printf("MOV      B = L"); break;
        case 0x46: printf("MOV      B = $HL"); break;
        case 0x47: printf("MOV      B = A"); break;
        case 0x48: printf("MOV      C = B"); break;
        case 0x49: printf("MOV      C = C"); break;
        case 0x4A: printf("MOV      C = D"); break;
        case 0x4B: printf("MOV      C = E"); break;
        case 0x4C: printf("MOV      C = H"); break;
        case 0x4D: printf("MOV      C = L"); break;
        case 0x4E: printf("MOV      C = $HL"); break;
        case 0x4F: printf("MOV      C = A"); break;
        case 0x50: printf("MOV      D = B"); break;
        case 0x51: printf("MOV      D = C"); break;
        case 0x52: printf("MOV      D = D"); break;
        case 0x53: printf("MOV      D = E"); break;
        case 0x54: printf("MOV      D = H"); break;
        case 0x55: printf("MOV      D = L"); break;
        case 0x56: printf("MOV      D = $HL"); break;
        case 0x57: printf("MOV      D = A"); break;
        case 0x58: printf("MOV      E = B"); break;
        case 0x59: printf("MOV      E = C"); break;
        case 0x5A: printf("MOV      E = D"); break;
        case 0x5B: printf("MOV      E = E"); break;
        case 0x5C: printf("MOV      E = H"); break;
        case 0x5D: printf("MOV      E = L"); break;
        case 0x5E: printf("MOV      E = $HL"); break;
        case 0x5F: printf("MOV      E = A"); break;
        case 0x60: printf("MOV      H = B"); break;
        case 0x61: printf("MOV      H = C"); break;
        case 0x62: printf("MOV      H = D"); break;
        case 0x63: printf("MOV      H = E"); break;
        case 0x64: printf("MOV      H = H"); break;
        case 0x65: printf("MOV      H = L"); break;
        case 0x66: printf("MOV      H = $HL"); break;
        case 0x67: printf("MOV      H = A"); break;
        case 0x68: printf("MOV      L = B"); break;
        case 0x69: printf("MOV      L = C"); break;
        case 0x6A: printf("MOV      L = D"); break;
        case 0x6B: printf("MOV      L = E"); break;
        case 0x6C: printf("MOV      L = H"); break;
        case 0x6D: printf("MOV      L = L"); break;
        case 0x6E: printf("MOV      L = $HL"); break;
        case 0x6F: printf("MOV      L = A"); break;
        case 0x70: printf("MOV      $HL = B"); break;
        case 0x71: printf("MOV      $HL = C"); break;
        case 0x72: printf("MOV      $HL = D"); break;
        case 0x73: printf("MOV      $HL = E"); break;
        case 0x74: printf("MOV      $HL = H"); break;
        case 0x75: printf("MOV      $HL = L"); break;
        case 0x76: printf("HLT"); break;
        case 0x77: printf("MOV      $HL = A"); break;
        case 0x78: printf("MOV      A = B"); break;
        case 0x79: printf("MOV      A = C"); break;
        case 0x7A: printf("MOV      A = D"); break;
        case 0x7B: printf("MOV      A = E"); break;
        case 0x7C: printf("MOV      A = H"); break;
        case 0x7D: printf("MOV      A = L"); break;
        case 0x7E: printf("MOV      A = $HL"); break;
        case 0x7F: printf("MOV      A = A"); break;
        case 0x80: printf("ADD      A += B"); break;
        case 0x81: printf("ADD      A += C"); break;
        case 0x82: printf("ADD      A += D"); break;
        case 0x83: printf("ADD      A += E"); break;
        case 0x84: printf("ADD      A += H"); break;
        case 0x85: printf("ADD      A += L"); break;
        case 0x86: printf("ADD      A += $HL"); break;
        case 0x87: printf("ADD      A += A"); break;
        case 0x88: printf("ADC      A += B"); break;
        case 0x89: printf("ADC      A += C"); break;
        case 0x8A: printf("ADC      A += D"); break;
        case 0x8B: printf("ADC      A += E"); break;
        case 0x8C: printf("ADC      A += H"); break;
        case 0x8D: printf("ADC      A += L"); break;
        case 0x8E: printf("ADC      A += $HL"); break;
        case 0x8F: printf("ADC      A += A"); break;
        case 0x90: printf("SUB      A -= B"); break;
        case 0x91: printf("SUB      A -= C"); break;
        case 0x92: printf("SUB      A -= D"); break;
        case 0x93: printf("SUB      A -= E"); break;
        case 0x94: printf("SUB      A -= H"); break;
        case 0x95: printf("SUB      A -= L"); break;
        case 0x96: printf("SUB      A -= $HL"); break;
        case 0x97: printf("SUB      A -= A"); break;
        case 0x98: printf("SBB      A -= B"); break;
        case 0x99: printf("SBB      A -= C"); break;
        case 0x9A: printf("SBB      A -= D"); break;
        case 0x9B: printf("SBB      A -= E"); break;
        case 0x9C: printf("SBB      A -= H"); break;
        case 0x9D: printf("SBB      A -= L"); break;
        case 0x9E: printf("SBB      A -= $HL"); break;
        case 0x9F: printf("SBB      A -= A"); break;
        case 0xA0: printf("ANA      A &= B"); break;
        case 0xA1: printf("ANA      A &= C"); break;
        case 0xA2: printf("ANA      A &= D"); break;
        case 0xA3: printf("ANA      A &= E"); break;
        case 0xA4: printf("ANA      A &= H"); break;
        case 0xA5: printf("ANA      A &= L"); break;
        case 0xA6: printf("ANA      A &= $HL"); break;
        case 0xA7: printf("ANA      A &= A"); break;
        case 0xA8: printf("XRA      A ^= B"); break;
        case 0xA9: printf("XRA      A ^= C"); break;
        case 0xAA: printf("XRA      A ^= D"); break;
        case 0xAB: printf("XRA      A ^= E"); break;
        case 0xAC: printf("XRA      A ^= H"); break;
        case 0xAD: printf("XRA      A ^= L"); break;
        case 0xAE: printf("XRA      A ^= $HL"); break;
        case 0xAF: printf("XRA      A ^= A"); break;
        case 0xB0: printf("ORA      A |= B"); break;
        case 0xB1: printf("ORA      A |= C"); break;
        case 0xB2: printf("ORA      A |= D"); break;
        case 0xB3: printf("ORA      A |= E"); break;
        case 0xB4: printf("ORA      A |= H"); break;
        case 0xB5: printf("ORA      A |= L"); break;
        case 0xB6: printf("ORA      A |= $HL"); break;
        case 0xB7: printf("ORA      A |= A"); break;
        case 0xB8: printf("CMP      A - B"); break;
        case 0xB9: printf("CMP      A - C"); break;
        case 0xBA: printf("CMP      A - D"); break;
        case 0xBB: printf("CMP      A - E"); break;
        case 0xBC: printf("CMP      A - H"); break;
        case 0xBD: printf("CMP      A - L"); break;
        case 0xBE: printf("CMP      A - $HL"); break;
        case 0xBF: printf("CMP      A - A"); break;
        case 0xC0: printf("RNZ      IF !Z, RET"); break;
        case 0xC1: printf("POP      BC = SP"); break;
        case 0xC2: printf("JNZ      IF !Z, %02x%02x", highorder, loworder);
            bytes_instruction = 3;
            break;
        case 0xC3: printf("JMP      %02x%02x", highorder, loworder);
            bytes_instruction = 3;
            break;
        case 0xC4: printf("CNZ      IF !Z, CALL %02x%02x", highorder, loworder);
            bytes_instruction = 3;
            break;
        case 0xC5: printf("PUSH     SP = BC"); break;
        case 0xC6: printf("ADI      A += %02x", loworder);
            bytes_instruction = 2;
            break;
        case 0xC7: printf("RST      CALL $0"); break;
        case 0xC8: printf("RZ       IF Z, RET"); break;
        case 0xC9: printf("RET      PC = SP"); break;
        case 0xCA: printf("JZ       IF Z, PC = %02x%02x", highorder, loworder);
            bytes_instruction = 3;
            break;
        case 0xCB: printf("NOP"); break;
        case 0xCC: printf("CZ       IF Z, CALL %02x%02x", highorder, loworder);
            bytes_instruction = 3;
            break;
        case 0xCD: printf("CALL     %02x%02x", highorder, loworder);
            bytes_instruction = 3;
            break;
        case 0xCE: printf("ACI      A += %02x", loworder);
            bytes_instruction = 2;
            break;
        case 0xCF: printf("RST      CALL $8"); break;
        case 0xD0: printf("RNC      IF !C, RET"); break;
        case 0xD1: printf("POP      DE = SP"); break;
        case 0xD2: printf("JNC      IF !C, %02x%02x", highorder, loworder);
            bytes_instruction = 3;
            break;
        case 0xD3: printf("OUT      Special");
            bytes_instruction = 2;
            break;
        case 0xD4: printf("CNC      IF !C, CALL %02x%02x", highorder, loworder);
            bytes_instruction = 3;
            break;
        case 0xD5: printf("PUSH     SP = DE"); break;
        case 0xD6: printf("SUI      A -= %02x", loworder);
            bytes_instruction = 2;
            break;
        case 0xD7: printf("RST      CALL $10"); break;
        case 0xD8: printf("RC       IF C, RET"); break;
        case 0xD9: printf("NOP"); break;
        case 0xDA: printf("JC       IF C, PC = %02x%02x", highorder, loworder);
            bytes_instruction = 3;
            break;
        case 0xDB: printf("IN       Special");
            bytes_instruction = 2;
            break;
        case 0xDC: printf("CC       IF C, CALL %02x%02x", highorder, loworder);
            bytes_instruction = 3;
            break;
        case 0xDD: printf("NOP"); break;
        case 0xDE: printf("SBI      A -= %02x", loworder);
            bytes_instruction = 2;
            break;
        case 0xDF: printf("RST      CALL $18"); break;
        case 0xE0: printf("RPO      IF !P, RET"); break;
        case 0xE1: printf("POP      HL = SP"); break;
        case 0xE2: printf("JPO      IF !P, %02x%02x", highorder, loworder);
            bytes_instruction = 3;
            break;
        case 0xE3: printf("XTHL     L = $SP, H = $SP + 1"); break;
        case 0xE4: printf("CPO      IF !P, CALL %02x%02x", highorder, loworder);
            bytes_instruction = 3;
            break;
        case 0xE5: printf("PUSH     SP = HL"); break;
        case 0xE6: printf("ANI      A &= %02x", loworder);
            bytes_instruction = 2;
            break;
        case 0xE7: printf("RST      CALL $20"); break;
        case 0xE8: printf("RPE      IF P, RET"); break;
        case 0xE9: printf("PCHL     PC = HL"); break;
        case 0xEA: printf("JPE      IF P, SP = %02x%02x", highorder, loworder);
            bytes_instruction = 3;
            break;
        case 0xEB: printf("XCHG     DL = HE; HE = DL");
            bytes_instruction = 2;
            break;
        case 0xEC: printf("CPE      IF P, CALL %02x%02x", highorder, loworder);
            bytes_instruction = 3;
            break;
        case 0xED: printf("NOP"); break;
        case 0xEE: printf("XRI      A ^= %02x", loworder);
            bytes_instruction = 2;
            break;
        case 0xEF: printf("RST      CALL $28"); break;
        case 0xF0: printf("RP       IF !S, RET"); break;
        case 0xF1: printf("POP      FLAGS/A = SP"); break;
        case 0xF2: printf("JP       IF !S, %02x%02x", highorder, loworder);
            bytes_instruction = 3;
            break;
        case 0xF3: printf("DI       DISABLE INTERRUPTS"); break;
        case 0xF4: printf("CP       IF !S, CALL %02x%02x", highorder, loworder);
            bytes_instruction = 3;
            break;
        case 0xF5: printf("PUSH     SP = FLAGS/A"); break;
        case 0xF6: printf("ORI      A |= %02x", loworder);
            bytes_instruction = 2;
            break;
        case 0xF7: printf("RST      CALL $30"); break;
        case 0xF8: printf("RM       IF S, RET"); break;
        case 0xF9: printf("SPHL     SP = HL"); break;
        case 0xFA: printf("JM       IF S, SP = %02x%02x", highorder, loworder);
            bytes_instruction = 3;
            break;
        case 0xFB: printf("EI       ENABLE INTERRUPTS"); break;
        case 0xFC: printf("CM       IF S, CALL %02x%02x", highorder, loworder);
            bytes_instruction = 3;
            break;
        case 0xFD: printf("NOP"); break;
        case 0xFE: printf("CPI      A - %02x", loworder);
            bytes_instruction = 2;
            break;
        case 0xFF: printf("RST      CALL $38"); break;
        default: break;
    }
    printf("\n");

    // Return pc to original position
    cpu->pc -= 3;

    return bytes_instruction;
}

void register_state(Cpu* cpu) {
    printf("a=%02x ", cpu->a);
    printf("b=%02x ", cpu->b);
    printf("c=%02x ", cpu->c);
    printf("d=%02x ", cpu->d);
    printf("e=%02x ", cpu->e);
    printf("h=%02x ", cpu->h);
    printf("l=%02x ", cpu->l);
    printf("sp=%04x ", cpu->sp);
    printf("pc=%04x ", cpu->pc);
    printf("s=%01x ", cpu->sf);
    printf("z=%01x ", cpu->zf);
    printf("a=%01x ", cpu->af);
    printf("p=%01x ", cpu->pf);
    printf("c=%01x ", cpu->cf);
    uint8_t f = 0;
    f |= cpu->sf << 7;
    f |= cpu->zf << 6;
    f |= cpu->af << 4;
    f |= cpu->pf << 2;
    f |= 1 << 1;
    f |= cpu->cf << 0;
    printf("flags=%02x", f);
    printf("\n");

}

void sys_call(Cpu* cpu) {
    if (cpu->pc == 0x05) {
        if (cpu->c == 0x02) {
            printf("%c", cpu->e);
        }
        else if (cpu->c == 0x09) {
            uint16_t i = (cpu->d << 8) | cpu->e;
            while (cpu_get_content_addr(cpu, i) != '$') {
                printf("%c", cpu_get_content_addr(cpu, i));
                i++;
            }
        }
    }
}

void print_memory(Cpu* cpu) {
    for (int i = 0; i < 0x1000; i++) {
        if (i % 16 == 0) printf("\n%08x ", i);
        printf("%02x ", *(cpu->memory + i));
    }
    printf("\n");
}